### PR TITLE
Added refresh button and reduced lag for large campaigns

### PR DESCRIPTION
**Pull request by S0larflare**
This is a really simple one, I've increased the automatic refresh time to 60 seconds and implemented a refresh button to manually kick off a refresh if desired. I also moved the refresh_message.hide() code to the end of the poll() function, so that it will show 'refreshing' until it is actually finished refreshing

Now with the actual files!

### CODE REVIEW

**Comment by jordan-wright** [comment]
Works for me! I'll review and merge this evening.

Thanks for working on this!

**Comment by S0larflare** [comment]
Just realised this has missed the campaign results page update, I really don't like how the browser pulls work. I'll see if I can sort it tomorrow

Sent from my iPhone

On 19 Mar 2017, at 21:27, Jordan Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


Works for me! I'll review and merge this evening.

Thanks for working on this!

**Comment by S0larflare** [comment]
I've added the updated campaign_results.html file. For some reason the entire campaign_results.js file is showing as different, and I can't fathom out why, some weird whitespace thing maybe?

**Comment by jordan-wright** [comment]
Yeah, probably some odd whitespace or newlines. I'll sort it out in a branch.

Thanks for taking this on!

**Pull request merged**
