### PR TITLE
Confirm password on registration or change

### LINKED ISSUE #180: confirm new password
it would be nice if the new password would be double checked to avoid typos

### PR DESCRIPTION
**Pull request by rcutmore**
This fixes #180 by adding password confirmation to the registration and password change pages. Let me know if any changes are needed to this.

### CODE REVIEW

**Comment by jordan-wright** [comment]
Awesome, thanks @rcutmore! I'll give this a lookover this afternoon and, if all looks good (on the surface it does), I'll merge it in.

Just as a heads up, make sure you've taken a look at the contributing.md file and are cool with it. It's standard stuff (almost a direct copy from some of my favorite projects), but just wanted to be on the up-and-up and make sure you were aware of it.

Thanks again!

**Comment by rcutmore** [comment]
Thanks for the heads up, I'm fine with everything in the contributing.md file.

**Comment by jordan-wright** [comment]
A bit of a nit pick, but is there any way we can change "password1" and "password2" to be "newPassword and "confirmPassword"? The same for "pw1" and "pw2"? I can see that making it easier to read down the line.

**Comment by jordan-wright** [comment]
Other than that one nit pick, everything looks great - excellent work! I'll merge once we have those var names updated.

**Comment by rcutmore** [comment]
No problem, the variable names are updated now.

**Comment by jordan-wright** [comment]
Merged - excellent work @rcutmore!

**Pull request merged**
