### PR TITLE
Add date parsing and manipulation for e-mail templates

### PR DESCRIPTION
**Pull request by dzsibi**
I added a new variable **{{ .Now }}** that contains the return value for time.Now when the template is executed. I also added three helper functions: **date**, **duration** and **location**, which can be used to parse a string into a Time, Duration or Location object, respectively. These changes allow templates to include references to the current (or specified) date and time. Examples:

Default formatting: {{ .Now }}
Custom formatting: {{ .Now.Format "01/02/2006 3:04 PM (MST)" }}
Custom formatting and time zone: {{ (.Now.In (location "Europe/Prague")).Format "01/02/2006 3:04 PM (MST)" }}

Issue #194 and a part of issue #1387 are relevant.

### CODE REVIEW

**Comment by H4xl0r** [comment]
Nice work

**Comment by H4xl0r** [comment]
Drops ERrors

template: template:53: function "location" not defined

 template: template:51:23: executing "template" at <.Now>: can't evaluate field Now in type models.PhishingTemplateContext

please fix !

**Comment by dzsibi** [comment]
Could you share with me the relevant part of the template you have been testing with?

**Comment by H4xl0r** [comment]
just opend a test template and added : 

Default formatting: {{ .Now }}
Custom formatting: {{ .Now.Format "01/02/2006 3:04 PM (MST)" }}
Custom formatting and time zone: {{ (.Now.In (location "Europe/Prague")).Format "01/02/2006 3:04 PM (MST)" }}

**Comment by dzsibi** [comment]
It's very likely that there is some problem with your build environment. On my installation, the template is evaluated to produce the following output:

Default formatting: 2019-05-30 12:22:07.571470298 +0000 UTC m=+1300465.258572099
Custom formatting: 05/30/2019 12:22 PM (UTC)
Custom formatting and time zone: 05/30/2019 2:22 PM (CEST)

Make sure you are issuing `go build` in the root directory of the gophish project, and that afterwards you are using the binary file generated in that folder, not (for example) in the bin directory where `go get` copies the original binary.

**Comment by H4xl0r** [comment]
Ok seems to be a build error ... so basicly just go get github/gophish ..etc
make the changes... go to the go github source folder of gopish... and then go build

**Comment by H4xl0r** [comment]
FIXED WAS BUILD ERROR

**Comment by jordan-wright** [comment]
Hi @dzsibi,

Thanks for sending this in! This looks good to me. The only request I'd make is that you please format the code using `gofmt`, which in this case will clean up indentation in some areas. Beyond that, this looks like it'll work as expected and will be a great addition to Gophish!

Thanks again for taking the time to implement this!

**Comment by dzsibi** [comment]
I pushed the files through gofmt, see commit above.

**Comment by jordan-wright** [comment]
Hey @dzsibi,

Thanks for running everything through `gofmt`! I'm going to go ahead and merge this into a branch, since it appears there will need to be a bit more work done before everything is fully ready to go. Particularly, it looks like we do some HTML escaping on the frontend before posting it back to the backend. This means that quoted values like `{{ .Now.Format "01/02/2006 3:04 PM (MST)" }}` used in a landing page result in a template parsing error.

Then, we'll need to add the variable to the autocomplete Javascript, which will be a much simpler problem to fix 😉 

Thanks again for taking the time to send this in! I'll finish out these two issues and hopefully that'll put us in good shape to get things merged into master.

**Comment by agentAA7** [comment]
when I try and save my email template when using {{ .Now }} I get an error:

> Error inserting template into database

Do I need to install some sort of patch to get this to work?
This is a fresh install using the latest version, the server is only 1 week old.

**Comment by ventra007** [comment]
Hi,
Is this still being worked on?
Running the Docker version of GoPhish and getting an error trying to save the Email Template:

` template: template:16:84: executing "template" at <.Now>: can't evaluate field Now in type models.PhishingTemplateContext`

**Comment by dzsibi** [comment]
@ventra007 I no longer use Gophish (we used it to run internal phishing tests at a company I used to work for), so I haven't actively worked on this PR for a long time now. If you look at the history of the PR, you can see that @jordan-wright merged it to a feature branch:

https://github.com/gophish/gophish/tree/1451-template-dates

The branch was then abandoned and never made its way to master. I agree with him that the feature needed additional work to integrate well with the UI. (I must admit that I never used the WYSIWYG editor, so I never encountered those issues.) I tried to fix some of these issues in #1524, but that was never even merged to the feature branch. If you only need the variable and the helper functions, you can try applying the patch to the latest version and use that as a custom build, it might work or it might not.

This also answers the question raised in issue #3050. There is nothing wrong with the current binary release. The feature was simply never finished or fully merged.

**Pull request merged**
