### PR TITLE
Fix code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
##### Description
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/gophish/issues/?category=recommended).

### Summary of changes
- Replace `time.Now().Sub` with `time.Since`
- Replace use of HTTP codes with constants
- Fix check for empty string
- Remove unnecessary comparison with bool

### CODE REVIEW

**Comment by jordan-wright** [comment]
Hi there,

Thanks for reaching out! These all seem like reasonable code quality improvements. 💚 

The only thing I'd ask is that you please remove the `deepsource.toml` file from the PR. I don't want to populate the repo with all sorts of meta files for various linters if I can avoid it, since those are yet another thing we need to maintain in the future. If you could please remove that file, then I'll merge this in.

**Comment by withshubh** [comment]
@jordan-wright :wave: 
I removed the `.deepsource.toml` file.

Also, I would like to share about DeepSource: It is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code.

I would really appreciate it if you could drop any suggestion on what we can do to onboard you (or gophish) on DeepSource in the future. :)

**Comment by jordan-wright** [comment]
Thanks again for sending this in.

I'm sure DeepSource is fine, but I'm not interested in adding more linter-specific metadata to the repo at this time.

**Comment by withshubh** [comment]
> Thanks again for sending this in.
> 
> I'm sure DeepSource is fine, but I'm not interested in adding more linter-specific metadata to the repo at this time.

No problem. :sparkling_heart:

**Pull request merged**
