### PR TITLE
Improve the Performance of Sending Emails

### PR DESCRIPTION
**Pull request by jordan-wright**
This PR improves the performance of sending emails. This works by caching just the relevant fields of a campaign once per batch of maillogs. This saves multiple database lookups and, as a result, reduces memory/CPU usage and sends emails significantly faster.

Some details can be found in https://github.com/gophish/gophish/issues/1726#issuecomment-578588154.

### CODE REVIEW

**Comment by edermi** [comment]
> Thanks for the follow-up! Just curious, if you sort the results in the UI by status, do you see any results with “Error”? This will help track down if they ever tried to send or if there was an error when sending. 

No, all mails have a green "Email Sent" badge.

**Comment by jordan-wright** [comment]
@edermi - Sorry for the delayed response.

That's definitely odd. I'm going to go ahead and merge this in for now since it seems to improve speed and have the same results we saw earlier regarding some emails not making it through.

If you get a chance, could you run the campaign again, dumping all the Gophish output to a file you can send my way? I think that'll help us track down which emails aren't getting sent and why. We can then tackle any bugs as needed.

Thanks for all your patience here!

**Comment by edermi** [comment]
No worries, thanks for implementing and merging the change.

I'll try to take a closer look again as soon as possible.

**Comment by edermi** [comment]
So, I found some time to test again today.

I built gophish from master today, used my scripts to fill gophish with test data and sent the mails, but only 4989 leave the server. Here is the log of the mail sending: https://gist.github.com/edermi/f66ab8d4e719229ed031fd57900725eb

I don't see any errors there, and these are in fact 4989 log lines indicating a mail was sent. Mailhog only receives 4989 mails but the set of targets is exactly 5k mail addresses.

**Pull request merged**
