### PR TITLE
Added total number of targets to campaign launch modal. enhancement #2946

### PR DESCRIPTION
**Pull request by w1gs**
This PR adds the total amount of targets to the launch campaign confirmation modal. Adds enhancement described at  #2946 .
Example: 
image

### CODE REVIEW

**Comment by FLX-0x00** [comment]
The min.js should not be part of a PR as reviewing this will cost too much time and there is too much potential for backdoors. The minifiy process will be done by the maintainers

**Comment by WigzyDev** [comment]
> The min.js should not be part of a PR as reviewing this will cost too much time and there is too much potential for backdoors. The minifiy process will be done by the maintainers

That makes sense. Thanks for letting me know. Is there a standard on formatting? Didn't see anything in the contributing.md and vscode applied my user settings formatting. The actual code for this PR is only a few lines in the unminified JS but the whole file was auto formatted.

**Comment by FLX-0x00** [comment]
If the maintainer wants to use special formatting, the .editorconfig file should be in the repo or a linting pipeline as a check. Can't see any of this here that indicates a general formatting convention. Thanks again for your work on this project!

**Comment by FLX-0x00** [comment]
maybe keep the pr open. just in case :)

**Pull request closed without merging**
