### PR TITLE
Upgraded SweetAlert2 from 4 to 8

### PR DESCRIPTION
**Pull request by glennzw**
GoPhish currently uses SweetAlert2 version 4.0.8, which is at least three years old (I couldn't find the actual release date). In keeping with the 'Beautiful Web UI' aspect of GoPhish I'd recommend upgrading to the latest version (8.16.3). This will give many more features, and make it easier for people to contribute (as it's quite hard finding documentation for version 4). To upgrade I did:

> swal.version
< "4.0.8"

`wget https://cdn.jsdelivr.net/npm/sweetalert2@8.16.3/dist/sweetalert2.min.css` 
`wget https://cdn.jsdelivr.net/npm/sweetalert2@8.16.3/dist/sweetalert2.min.js`

`mv sweetalert2.min.js static/js/src/vendor/sweetalert2.min.js  `
`mv sweetalert2.min.css static/css/sweetalert2.min.css`

```
npm install  
gulp
yarn run webpack
```

> swal.version
< "8.16.3"

As far as I can tell swal() is called in the following places:
```
grep "swal(" -ir * | grep -v min | cut -d ":" -f 1| sort|uniq -c
   5 static/js/src/app/campaign_results.js
   4 static/js/src/app/campaigns.js
   2 static/js/src/app/groups.js
   2 static/js/src/app/landing_pages.js
   2 static/js/src/app/sending_profiles.js
   2 static/js/src/app/templates.js
   2 static/js/src/app/users.js
```

The new SweetAlert2 version replaces the swal() call with Swal.fire(), and handles the Cancel button in a different way. I've made the following changes in the above files:

`user.js`
Delete user functionality; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅

`templates.js`
Delete template functionality; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅

`sending_profiles.js`
Delete sending profile functionality; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅

`landing_pages.js`
Delete landing page functionality; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅

`groups.js`
Delete groups functionality; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅

`campaigns.js`
Confirmation of launching campaign; replaced swal() with Swal.fire() and updated handling of cancel function. Tested.
Delete campaign functionality; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅

`campaign_results.js`
Delete campaign functionality; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅
Complete campaign functionality; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅
Replay function; replaced swal() with Swal.fire() and updated handling of cancel function. Tested ✅
  
 <br> 
There is an issue with Sweetalert2 fonts and dialogs being small, because of Bootstrap 3. I added the following to `main.css` as a workaround:

.swal2-popup {
  font-size: 1.6rem !important;
}

See:
https://github.com/sweetalert2/sweetalert2/issues/834

As far as I can tell the new swal dialogs look identical to the old ones, but we'll have the ability to change the looks in great news ways moving forward, as well as making dialog popups easier for future additions to the platform.

Final comment; GoPhish also uses Bootstrap 3.3.7, which is also three years old. It seems to be a bit more work to upgrade, but worth considering some time in the future to improve UI and keep with the times. For more migration info see https://getbootstrap.com/docs/4.0/migration/

### CODE REVIEW

**Comment by jordan-wright** [comment]
Hey @glennzw,

Thanks for sending this in! I definitely agree that some of our frontend dependencies are a bit old. That said, I'm a bit unsure of the best way to handle this right now. Typically, I try to stay away from merging minified JS - even if I trust the person submitting it.

In this case, perhaps what I'll do is merge this into a branch, verify the SweetAlert hashes from the upstream source and rebuild the minified JS files.

To get things in good shape, it looks like there might be some files missing from the commits. Would you mind adding all of the unminified Gophish JS files that you modified, plus `main.css`? I can then rebuild the minified files on my end. You're also free to add the sweetalert files, though I'll likely pull a fresh copy upstream.

And just to make sure I'm super clear - my hesitation to merging minified JS is just a broad rule until I can get some kind of CI pipeline set up to validate what's being submitted. It's certainly not any indication of distrust towards you. I'm super thankful for all the great work you're doing for Gophish!

Regarding Bootstrap- you're absolutely right. I've wanted to migrate to v4 for a long time now for multiple reasons. It'll be a challenge though. Gophish is far from the cleanest CSS and I seem to recall I started with a dashboard which used a customized Bootstrap v3, making it even more tricky.

I'd love to migrate the dashboard itself into something more modern. There are some amazing alternatives coming out now. Here are just a few that I like:

* [`airframe-react`](https://github.com/0wczar/airframe-react)
* [`AdminLTE`](https://github.com/ColorlibHQ/AdminLTE)
* [`coreui`](https://github.com/coreui/coreui-free-bootstrap-admin-template)
* [`tabler-react`](https://github.com/tabler/tabler-react)
* [`Adminator`](https://github.com/puikinsh/Adminator-admin-dashboard)

You can find more in my Github stars if you're interested. I'll likely open an RFC for people's opinions, though much of the qualification will be on how easy it'd be to port Gophish. For example, I'd love to lean towards something that's build by default with BS4 and React.

**Comment by glennzw** [comment]
Hi @jordan-wright, thanks for your reply. I was unsure how you handle minimised files. Completely agree - I wouldn't want minimised files from other people being merged in either. In the future is it best to just include foo.js files?

Also, I seem to have botched this pull request, I think the `yarn` commit seems to have rolled everything back to the old swal! I'll try and rectify it ASAP. Git gremlins 🤷🏻‍♂️

It's be great to migrate the dashboard into something modern. From your list I love the look of airframe-react, tabler-react, and Adminator. I'll give it some thought too and dig around with what's new and cool. It's great how GoPhish is API driven though, so should make it easier to migrate!

**Comment by jordan-wright** [comment]
Hey @glennzw,

Yep! If you could just send up the unminified .js files, that'd be great. That way, I can merge them into a branch, minify everything, then merge into master.

**Comment by glennzw** [comment]
Hi @jordan-wright - sorry about the triple-commit. I think I have it right this time. I've added the following files:

```
static/css/main.css
static/js/src/app/campaign_results.js
static/js/src/app/campaigns.js
static/js/src/app/groups.js
static/js/src/app/landing_pages.js
static/js/src/app/sending_profiles.js
static/js/src/app/templates.js
static/js/src/app/users.js
```

I've tested the new SweetAlert dialogs on Chrome on my Mac and all seem to work. The only edge case I didn't manage to test in browser was in `campaigns.js` where the API returns an error and we close the Swal dialog; [this line of code](https://github.com/glennzw/gophish/blob/swal-update/static/js/src/app/campaigns.js#L65).


If it's easier I also created a new branch with just one commit and just the JavaScript files and main.css: https://github.com/glennzw/gophish/tree/swal-update-clean

**Comment by glennzw** [comment]
A sneak preview of what we can accomplish with the new Sweetalert :)

wizard

**Comment by jordan-wright** [comment]
Hey @glennzw!

Thanks for following up on this one! I’m excited about upgrading our dependencies, since it always leads to neat features.

You and I are on the same page that our campaign builder could use refactoring. I had some initial thoughts in https://github.com/gophish/gophish/issues/223 but haven’t gotten around to finishing it up. Now that the codebase is evolving I think it will make a good first project for React.

That said, I think the flow we’d be looking for will be a bit advanced for what sweetalert can give us. Still excited to get this merged in though!

**Comment by jordan-wright** [comment]
Hey @glennzw!

I'm going to go ahead and merge this into a branch where I can rebuild the .min.js files as well as include the new sweetalert version. My hope is to get everything merged into `master` this evening.

Thanks again for your great work on this!

**Comment by jepunband** [comment]
hello, any updates on this guys? GoPhish is not showing menus/dashboard on mobile view.

**Pull request merged**
