### PR TITLE
Implemented Polling for Campaign Updates

### LINKED ISSUE #148: Polling for Updates on Campaign Results
Refreshing the campaign results page manually is for barbarians - this is 2016.

I'm proposing we at least poll the API for the campaign results every *x* seconds and update the results accordingly.

### PR DESCRIPTION
**Pull request by jordan-wright**
Implemented real time polling for campaign updates.

Fixes #148.

@wjwoodson @StrangeUSB can one of y'all give this a shot if you have the chance?

### CODE REVIEW

**Comment by wjwoodson** [comment]
The polling appears to be working as expected, campaign results/phish timeline are updated live (10 seconds)

Not sure if it is my test email and/or recipient, but I did have issues with inserting a valid tracking link/page hit rid into the email:


`will@test:~/gophish$ sudo cat /var/spool/mail/test`
From testsender@localhost  Wed Feb 24 19:13:15 2016
Return-Path: <testsender@localhost>
X-Original-To: test@localhost
Delivered-To: test@localhost
Received: from localhost (localhost [127.0.0.1])
	by t1000 (Postfix) with ESMTPS id 625F06E0312
	for <test@localhost>; Wed, 24 Feb 2016 19:13:15 -0600 (CST)
Content-Type: multipart/mixed;
 boundary=ddd6046c258dccfac363d9f77bc1caf02e847eeb494266c39c26fb0ffc7c
To: test@localhost
Subject: test_with_tracking
Message-Id: <1456362795394910089.9204.3170177857652497336@t1000>
From: test_sender <testsender@localhost>
Date: Wed, 24 Feb 2016 19:13:15 -0600
Mime-Version: 1.0

--ddd6046c258dccfac363d9f77bc1caf02e847eeb494266c39c26fb0ffc7c
Content-Type: multipart/alternative;
 boundary=d0cf6510fd2f6e1fa4e5c306409773d0ceb1c08e84af22408ab465bd8f58

--d0cf6510fd2f6e1fa4e5c306409773d0ceb1c08e84af22408ab465bd8f58
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Test! tracker is: `http://localhost:80/track?rid=3D5c9574b72a3fdf311ef5799dc=`
`e5d0c3c27d40f5c2cf1c94497590598392bb673`
--d0cf6510fd2f6e1fa4e5c306409773d0ceb1c08e84af22408ab465bd8f58
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

`http://localhost:80/track?rid=3D5c9574b72a3fdf311ef5799dce5d0c3c27d40f5c2cf=`
`1c94497590598392bb673`
--d0cf6510fd2f6e1fa4e5c306409773d0ceb1c08e84af22408ab465bd8f58--

--ddd6046c258dccfac363d9f77bc1caf02e847eeb494266c39c26fb0ffc7c--

`will@test:~/gophish$ sqlite3 gophish.db '.dump results'`
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "results" ("id" integer primary key autoincrement,"campaign_id" bigint,"user_id" bigint,"r_id" varchar(255),"email" varchar(255),"first_name" varchar(255),"last_name" varchar(255),"status" varchar(255) NOT NULL ,"ip" varchar(255),"latitude" real,"longitude" real , position VARCHAR(255));
INSERT INTO "results" VALUES(2,3,1,'`fd4c1ef5a9419a2000f9a08c21f2013197e8aab136e58eebcdbc2fa82177edbe`','test@localhost','test2_first','test2_last','Email Sent','',0.0,0.0,'test2_pos');
COMMIT;

`will@test:~/gophish$ sqlite3 gophish.db '.dump templates'`
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "templates" ("id" integer primary key autoincrement,"user_id" bigint,"name" varchar(255),"subject" varchar(255),"text" varchar(255),"html" varchar(255),"modified_date" datetime );
INSERT INTO "templates" VALUES(2,1,'test_with_tracking','test_with_tracking','Test! tracker is: {{.TrackingURL}}','{{.TrackingURL}}','2016-02-24 19:12:21.502827761-06:00');
COMMIT;


The embedded ids return 404, while inserting the rid from the db row is tracked as expected.

**Comment by jordan-wright** [comment]
Interesting.. we might have to check that. Those id's should definitely not be different.

Can you replicate that on master? You should be able to just check it out and re run the same campaign. All my changes were JS.

**Comment by wjwoodson** [comment]
Yes, also occurs in master.

**Comment by jordan-wright** [comment]
Ok, we'll take a look at that.

For now, polling works? When you hit the tracker and the click link, you saw that reflected in the results via polling? Did you have the timeline open (it's crazy watching that happen!)

**Pull request merged**
