### PR TITLE
Postgres support

### PR DESCRIPTION
**Pull request by m1nl**
Similarly to pull request from @svigne1, I have implemented basic support for PostgreSQL database backend. I have also included a fix, which prevents from adding a duplicate admin account to the database.

### CODE REVIEW

**Comment by jordan-wright** [comment]
Nice! Let me take a look at the pull req a little closer and do some testing and I'll see if we can get this merged.

Thanks for looking into this!

**Comment by michaelekaufman** [comment]
Thanks for your work on this project. I would like to use postgres instead of mysql.
Will this PR be merged?

**Comment by mohdnajdy** [comment]
when will this be merged ?

**Comment by m1nl** [comment]
just to let you know, I’m not longer monitoring this PR as I’ve created my own open source phishing simulation tool called pompa (which uses postgres btw ;)

**Comment by mohdnajdy** [comment]
@jordan-wright

**Comment by jordan-wright** [comment]
Hi everyone,

I’ve decided that I’m not going to add Postgres support at this time. I don’t personally use Postgres, and we have MySQL support for those who don’t wish to use SQLite.

Thanks to @m1nl for sending the initial PR! Please keep the feature suggestions and ideas coming!

**Pull request closed without merging**
